### ISSUE TITLE
Failure on Get-ODStatus - unhandled exception

### ISSUE THREAD

**Issue by schapmanWT** [rodneyviana/ODSyncService#38]
Hi,

i got the module installed and when i run the Get-ODStatus i get the following:

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Native.API.GetStatusByTypeApi(String SyncRootId, OneDriveState& State)
   at Native.API.GetStateBySyncRootId(String SyncRootId, OneDriveState& State)
   at OdSyncService.OdSyncStatusWS.GetStatus()
   at OneDriveLib.GetStatus.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   at System.Management.Automation.CommandProcessorBase.DoExecute()
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.DlrScriptCommandProcessor.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.DlrScriptCommandProcessor.Complete()
   at System.Management.Automation.CommandProcessorBase.DoComplete()
   at System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(CommandProcessorBase commandRequestingUpstreamCommandsToStop)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   at System.Management.Automation.Runspaces.PipelineThread.WorkerProc()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

[process exited with code 3221225477 (0xc0000005)]

My machine is running windows 11 dev - Microsoft Windows [Version 10.0.22623.875]

Let me know what other information you need.

Thanks in advance for any assistance.

**Comment by homotechsual** [comment]
Just to say can reproduce this.

**Comment by AlecMcCutcheon** [comment]
Having this issue also

**Comment by AlecMcCutcheon** [comment]
I figured it out guys, use https://github.com/rodneyviana/ODSyncService/releases/latest/download/OneDriveLib.dll, not the DLL that is in the binaries folder

**Comment by AlecMcCutcheon** [comment]
You guys really should not have a broken DLL file in your binaries folder to begin with but at least your latest release seems to actually not be bugged
