### ISSUE TITLE
 <ERROR>Status not found for type

### ISSUE THREAD

**Issue by peter-peterhodgkinson-tech** [rodneyviana/ODSyncService#41]
hi,

Using OneDriveLib 1.0.7796.25985 with OneDrive version: Build 23.043.0226.0001 (64-bit)

I have three OneDrives synced to my PC, a Personal Microsoft account, a Business OneDrive and a SharePoint Library.

It used to be that the Personal and Business OneDrives would return the correct StatusString and the SharePoint Library would error. However, recently all three have started returning a StatusString beginning with <ERROR>Status not found for type

For example:
StatusString : <ERROR>Status not found for type [OneDrive - Personal]

I know that I have not updated OneDriveLib but my OneDrive client is looking different to me so I am strongly suspecting that an update to the OneDrive client means that OneDriveLib no longer works.

Kindest Regards

Peter

**Comment by rodneyviana** [comment]
Hi Peter,

I have a beta version of a much better cmdLet. If you want to help me test this version I can release the new version. What’s the Windows version we are using?

**Comment by peter-peterhodgkinson-tech** [comment]
hi rodneyviana,

I'm on Windows 11 22H2. More than happy to test.

Kindest Regards

Peter

**Comment by rodneyviana** [comment]
Go here:
Try the standalone app StorageApp.exe (not PowerShell): [StorageApp.exe](https://github.com/rodneyviana/ODSyncService/blob/master/Binaries/Beta/StorageApp.exe)

If it works, try the beta cmdlet [OneDriveFlyoutPS.dll](https://github.com/rodneyviana/ODSyncService/blob/master/Binaries/Beta/OneDriveFlyoutPS.dll)
 Let me know the results. (We may need to troubleshoot the OneDriveFlyoutPS.dll)

**Comment by peter-peterhodgkinson-tech** [comment]
hi Rodney,

My apologies for the delay in getting back to you - I've had busy days at work Friday though Sunday and then my PC has been hard at work encoding videos.

I do, however, have an update on where I have got to.

Firstly, my OneDrive client has updated since I first made the report. I am now one OneDrive Build 23.048.0305.0002 (64-bit)

StorageApp.exe works fine for me.

Having a few issues with OneDriveFlyoutPS.dll

`Import-Module: Bad IL format. The format of the file 'path:\redacted\OneDriveFlyoutPS.dll' is invalid.` 

with Get-Error reporting a HResult of : -2147024885

I am still trying to work out what is going on there at the moment, when I have made more progress on that I will update.

Kindest Regards

Peter

**Comment by rodneyviana** [comment]
Hi Peter,

I send you the wrong path to the cmdlet, no wonder it didn't work. The PowerShell version is actually compiled and signed. It's just not available as a release. This time I downloaded and tested and it brings the new API implementation. This works well for me, but I never tested on an environment like yours.
Please use this link: https://github.com/rodneyviana/ODSyncService/blob/master/Binaries/PowerShell/OneDriveLib.dll

It should look like:
```
Get-ODStatus


SyncRootId      : OneDrive!S-1-5-21-124525095-708859637-1545119021-908052!Business1|10935082bea94993a9037f7a6
                  709947e
LocalPath       : C:\Users\rviana\OneDrive - Contoso
UserSID         : S-1-5-21-124525095-708859637-1545119021-908052
UserName        : CONTOSO\rviana
NewApiStatus    : 0
DisplayName     : OneDrive - Contoso
ServiceType     : Business1
StatusString    : Synced
IconPath        : file:///C:/Users/rviana/AppData/Local/Microsoft/OneDrive/23.061.0319.0001/images/darkTheme/CloudIconSynced.svg
QuotaLabel      : 70.3 GB used of 5 TB (1%)
QuotaTotalBytes : 5497558138880
QuotaUsedBytes  : 75498746362
QuotaColor      : A: 255, R: 96, G: 205, B: 255
IsNewApi        : True

SyncRootId      : OneDrive!S-1-5-21-124525095-708859637-1545119021-908052!Personal|B7C3EE2A336CFE2E!125
LocalPath       : C:\Users\rviana\OneDrive
UserSID         : S-1-5-21-124525095-708859637-1545119021-908052
UserName        : CONTOSO\rviana
NewApiStatus    : 1
DisplayName     : OneDrive - Personal
ServiceType     : Personal
StatusString    : Syncing
IconPath        : file:///C:/Users/rviana/AppData/Local/Microsoft/OneDrive/23.061.0319.0001/images/darkTheme/CloudIconSyncing.svg
QuotaLabel      : 259.5 GB used of 1 TB (23%)
QuotaTotalBytes : 1166083620864
QuotaUsedBytes  : 278644453234
QuotaColor      : A: 255, R: 96, G: 205, B: 255
IsNewApi        : True

```

**Comment by peter-peterhodgkinson-tech** [comment]
Hi Rodney,

Good news is that I have the correct dll now.

I am getting into an error state, at this time I am investigating if there is an issue with some security software on my PC. I will get back to you after I have done some more testing.

However, because it is easier for me to post the error here now I will do so and then carry on my investigation.

`Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at Native.API.GetStatusByTypeApi(System.String, Native.OneDriveState ByRef)
--------------------------------
   at Native.API.GetStateBySyncRootId(System.String, Native.OneDriveState ByRef)
   at OdSyncService.OdSyncStatusWS.GetStatus()
   at OneDriveLib.GetStatus.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   at System.Management.Automation.CommandProcessorBase.DoExecute()
   at System.Management.Automation.Internal.PipelineProcessor.Inject(System.Object, Boolean)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object)
   at System.Management.Automation.PipelineOps.InvokePipeline(System.Object, Boolean, System.Management.Automation.CommandParameterInternal[][], System.Management.Automation.Language.CommandBaseAst[], System.Management.Automation.CommandRedirection[][], System.Management.Automation.Language.FunctionContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.Interpreter.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon)
   at System.Management.Automation.DlrScriptCommandProcessor.RunClause(System.Action`1<System.Management.Automation.Language.FunctionContext>, System.Object, System.Object)
   at System.Management.Automation.DlrScriptCommandProcessor.Complete()
   at System.Management.Automation.CommandProcessorBase.DoComplete()
   at System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(System.Management.Automation.CommandProcessorBase)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProcImpersonate()
   at System.Management.Automation.Runspaces.PipelineThread.WorkerProc()
   at System.Threading.Thread+StartHelper.Callback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Thread.StartCallback()`

I hope you like interesting errors.

Kindest Regards

Peter

**Comment by chrisshearing** [comment]
We are having the exact same issue with the release version and the same error from the beta,

Did your investigation find anything @peter-peterhodgkinson-tech ?

Thanks!

**Comment by SnowDogDad** [comment]
I am having the exact same issue with the new DLL.  Just downloaded OneDriveLib.DLL today (v1.0.8257.21118). 

OneDrive build 23.137.0702.0001

**Comment by illiad1975** [comment]
I'm also having the exact same issue too, now.

**Comment by DavidD065** [comment]
Also getting the same issue:

OneDrive version: Build 23.204.1001.0003 (64-bit)

OS:
Windows 11 Pro
Version 22621.2283
Build 22H2

DLL Version (latest)
1.0.7796.25985

Works on Win10 Enterprise, Version 10.0.19045 Build 19045

**Comment by rodneyviana** [comment]
Try this new version:
https://github.com/rodneyviana/ODSyncUtil/
